// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using T2S.Test.Data;

namespace T2S.Test.Migrations
{
    [DbContext(typeof(ConteinerContext))]
    partial class ConteinerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("T2S.Test.Models.Conteiner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumCntr")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Conteiner");
                });

            modelBuilder.Entity("T2S.Test.Models.ConteinerMovimentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ConteinerId")
                        .HasColumnType("int");

                    b.Property<int>("MovimentacaoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConteinerId");

                    b.HasIndex("MovimentacaoId");

                    b.ToTable("ConteinerMovimentacao");
                });

            modelBuilder.Entity("T2S.Test.Models.Movimentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Navio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoMovimentacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movimentacao");
                });

            modelBuilder.Entity("T2S.Test.Models.ConteinerMovimentacao", b =>
                {
                    b.HasOne("T2S.Test.Models.Conteiner", "Conteiner")
                        .WithMany("ConteinerMovimentacao")
                        .HasForeignKey("ConteinerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("T2S.Test.Models.Movimentacao", "Movimentacao")
                        .WithMany("ConteinerMovimentacao")
                        .HasForeignKey("MovimentacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conteiner");

                    b.Navigation("Movimentacao");
                });

            modelBuilder.Entity("T2S.Test.Models.Conteiner", b =>
                {
                    b.Navigation("ConteinerMovimentacao");
                });

            modelBuilder.Entity("T2S.Test.Models.Movimentacao", b =>
                {
                    b.Navigation("ConteinerMovimentacao");
                });
#pragma warning restore 612, 618
        }
    }
}
